In [53]:
import numpy as np
a=np.random.random((2,2))
b=np.random.random((4,3,2))
c=np.random.random((5,4,3,2))


In [6]:
a

array([[0.57146542, 0.39102836],
       [0.87138355, 0.91782751]])

In [13]:
print(a[0])
print('''''')
print(a[:,0])
print('''''')

print(c[0])

print('''''')
print(c[0,1])
print('''''')
print(c[0,1,2])
print('''''')
print(c[0,1,2,1])


[0.57146542 0.39102836]

[0.57146542 0.87138355]

[[[0.19228848 0.21296647]
  [0.26214278 0.77442719]
  [0.42213081 0.21201468]]

 [[0.13835264 0.91991582]
  [0.8069805  0.98167188]
  [0.21450509 0.45481571]]

 [[0.90582422 0.26414144]
  [0.80085354 0.34246335]
  [0.54030682 0.70519982]]

 [[0.75211872 0.09986986]
  [0.63407618 0.55586286]
  [0.53528561 0.40887344]]]

[[0.13835264 0.91991582]
 [0.8069805  0.98167188]
 [0.21450509 0.45481571]]

[0.21450509 0.45481571]

0.45481571090503403


In [15]:
np.sum(a)

2.7517048463026494

In [17]:
a

array([[0.57146542, 0.39102836],
       [0.87138355, 0.91782751]])

In [19]:
a.sum(axis=1)

array([0.96249378, 1.78921106])

In [21]:
np.sum(a,axis=1)

array([0.96249378, 1.78921106])

In [22]:
b

array([[[0.71261356, 0.14568227],
        [0.08311616, 0.43998719],
        [0.00165981, 0.3001898 ]],

       [[0.64554238, 0.23015629],
        [0.14684767, 0.99873054],
        [0.10176956, 0.13209149]],

       [[0.93611283, 0.17820963],
        [0.53368757, 0.34316178],
        [0.4142357 , 0.72270767]],

       [[0.88268138, 0.93877153],
        [0.21163223, 0.29110529],
        [0.57752339, 0.79346662]]])

In [23]:
b.mean()

0.4484034312264828

In [26]:
b.mean(axis=2)

array([[0.42914791, 0.26155167, 0.15092481],
       [0.43784934, 0.5727891 , 0.11693053],
       [0.55716123, 0.43842468, 0.56847168],
       [0.91072646, 0.25136876, 0.68549501]])

In [27]:
b+2

array([[[2.71261356, 2.14568227],
        [2.08311616, 2.43998719],
        [2.00165981, 2.3001898 ]],

       [[2.64554238, 2.23015629],
        [2.14684767, 2.99873054],
        [2.10176956, 2.13209149]],

       [[2.93611283, 2.17820963],
        [2.53368757, 2.34316178],
        [2.4142357 , 2.72270767]],

       [[2.88268138, 2.93877153],
        [2.21163223, 2.29110529],
        [2.57752339, 2.79346662]]])

In [28]:
b-1

array([[[-0.28738644, -0.85431773],
        [-0.91688384, -0.56001281],
        [-0.99834019, -0.6998102 ]],

       [[-0.35445762, -0.76984371],
        [-0.85315233, -0.00126946],
        [-0.89823044, -0.86790851]],

       [[-0.06388717, -0.82179037],
        [-0.46631243, -0.65683822],
        [-0.5857643 , -0.27729233]],

       [[-0.11731862, -0.06122847],
        [-0.78836777, -0.70889471],
        [-0.42247661, -0.20653338]]])

In [29]:
list(b)-1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [54]:
a=np.random.random((2,2))
b=np.random.random((2,2))

In [32]:
a,b

(array([[0.52151879, 0.28388218],
        [0.62032651, 0.43355296]]), array([[0.76807349, 0.59536887],
        [0.33216294, 0.1781077 ]]))

In [35]:
np.add(a,b)

array([[1.28959228, 0.87925105],
       [0.95248945, 0.61166066]])

In [36]:
a+b

array([[1.28959228, 0.87925105],
       [0.95248945, 0.61166066]])

In [37]:
a-b

array([[-0.2465547 , -0.31148668],
       [ 0.28816357,  0.25544525]])

In [39]:
np.subtract(a,b)

array([[-0.2465547 , -0.31148668],
       [ 0.28816357,  0.25544525]])

In [40]:
np.add(a,-b)

array([[-0.2465547 , -0.31148668],
       [ 0.28816357,  0.25544525]])

In [41]:
np.multiply(a,b)

array([[0.40056476, 0.16901461],
       [0.20604948, 0.07721912]])

In [42]:
a*b

array([[0.40056476, 0.16901461],
       [0.20604948, 0.07721912]])

In [43]:
np.matmul(a,b)

array([[0.4948599 , 0.36105766],
       [0.62046657, 0.44654221]])

In [44]:
np.matmul(b,a)

array([[0.76988785, 0.47616631],
       [0.28371415, 0.17151426]])

In [46]:
b*a

array([[0.40056476, 0.16901461],
       [0.20604948, 0.07721912]])

In [47]:
np.divide(a,b)

array([[0.67899596, 0.47681731],
       [1.86753679, 2.43421789]])

In [49]:
np.e

2.718281828459045

In [51]:
import os

In [52]:
if os.path.exists(os.path.join("C:", "ironhack","module_0", "python", "data")) == False:
    os.makedirs(os.path.join("C:", "ironhack","module_0", "python", "data"))
else:
    os.chdir(os.path.join("C:", "ironhack","module_0", "python", "data"))



'C:ironhack\\module_0\\python\\data'

In [55]:
a.transpose()

array([[0.43601833, 0.19661999],
       [0.41320029, 0.25375346]])

In [56]:
np.transpose(a)

array([[0.43601833, 0.19661999],
       [0.41320029, 0.25375346]])

In [61]:
a.T

array([[0.43601833, 0.19661999],
       [0.41320029, 0.25375346]])

In [63]:
import pandas as pd

In [69]:
d = {"key1":[1,2,3], "key2":("crock", 2, 3), "key3":{4,5,6}}
df = pd.DataFrame(d).transpose()
df.sum(axis = 1)

key1    0.0
key2    0.0
key3    0.0
dtype: float64

In [78]:
df.iloc[0].sum()

6

In [73]:
df

0          1          2
key1          1          2          3
key2      crock          2          3
key3  {4, 5, 6}  {4, 5, 6}  {4, 5, 6}